name: Marketplace Actions

on:
  issues:
    types:
      - opened
      - reopened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  parse-issue:
    
    if: failure() == false && github.event.issue.state == 'open'
    name: Parse Issue
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUM: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    outputs:
      result: ${{ steps.run.outputs.result }}
      output: ${{ steps.run.outputs.output }}
      type: ${{ steps.run.outputs.type }}
      name: ${{ steps.run.outputs.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
    
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        id: run
        env:
          TITLE: ${{ env.ISSUE_TITLE }}
          PYPI_NAME: "alicebot"
        run: python .github/actions_scripts/parse.py

  test:
    runs-on: ubuntu-latest
    needs: 
      - parse-issue
    steps:
      - uses: actions/checkout@v3
            # Set up Python 3.6 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Set up cache for pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: print
        env:
          OUTPUT: ${{ needs.parse-issue.outputs.output }}
          TYPE: ${{ needs.parse-issue.outputs.type }}
          NAME: ${{ needs.parse-issue.outputs.name }}
          RESULT: ${{ needs.parse-issue.outputs.result }}
        run: |
          echo "OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT
          echo "TYPE=$TYPE" >> $GITHUB_OUTPUT
          echo "NAME=$NAME" >> $GITHUB_OUTPUT
          echo "RESULT=$RESULT" >> $GITHUB_OUTPUT