name: Extension validation

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.validate.outputs.repository }}
      validation_output: ${{ steps.validate.outputs.validation_output }}
      result: ${{ steps.validate.outputs.result }}
    steps:
      - name: Parse issue body
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.1

      - name: Find plugin repository
        id: set-output
        env:
          JSON_DATA: ${{ steps.parse.outputs.data }}
        run: |
          repository=$(echo $JSON_DATA | jq -r '.["alice-bot-plugin-repository-name"].text' )
          echo "repository=$repository" >> $GITHUB_OUTPUT

      - name: Ensure repository is filled
        if: steps.set-output.outputs.repository == 'null'
        env:
          PARSED_DATA: ${{ steps.parse.outputs.data }}
        run: |
          # Check if $GITHUB_STEP_SUMMARY exist to avoid the following lines to error when running with act
          if [[ -w "$GITHUB_STEP_SUMMARY" ]]; then
            echo "No repository found in the body of the issue ${{ inputs.issue_number }}" >> $GITHUB_STEP_SUMMARY
            echo "Is the \"alice-bot-plugin-repository-name\" field present?" >> $GITHUB_STEP_SUMMARY
            echo $PARSED_DATA >> $GITHUB_STEP_SUMMARY
          fi
          exit 1

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate repository
        id: validate
        env:
          REPOSITORY: ${{ steps.set-output.outputs.repository }}
        run: node .github/actions-scripts/validate.js

  validation-succeeded:
    runs-on: ubuntu-latest
    needs: parse-issue
    if: needs.parse-issue.outputs.result == 'success'
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Render template
        id: render
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/workflows/templates/validation-succeeded.md
          vars: |
            extension: ${{ needs.parse-issue.outputs.validation_output }}
            content: ${{ needs.parse-issue.outputs.repository }}

      - name: Add Comment
        if: env.ACT == false
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.render.outputs.result }}

      - name: Remove label validation/failed
        if: env.ACT == false && contains(github.event.issue.labels.*.name, 'validation/failed')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["validation/failed"]
            })

      - name: Add label validation/succeeded
        if: env.ACT == false && !contains(github.event.issue.labels.*.name, 'validation/succeeded')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["validation/succeeded"]
            })

  validation-failed:
    runs-on: ubuntu-latest
    needs: parse-issue
    if: needs.parse-issue.outputs.result == 'failure'
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Render template
        id: render
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/workflows/templates/validation-failed.md
          vars: |
            extension: ${{ needs.parse-issue.outputs.repository }}
            validation_output: ${{ toJSON(format('{0}{1}', needs.parse-issue.outputs.validation_output,needs.parse-issue.outputs.validation_output)) }}

      - name: Add comment
        if: env.ACT == false
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.render.outputs.result }}


      - name: Remove label validation/succeeded
        if: env.ACT == false && contains(github.event.issue.labels.*.name, 'validation/succeeded')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["validation/succeeded"]
            })

      - name: Add label validation/failed
        if: env.ACT == false && !contains(github.event.issue.labels.*.name, 'validation/failed')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["validation/failed"]
            })

      - name: Mark job as failed
        run: exit 1
