name: Extension validation

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUM: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    outputs:
      repository: ${{ steps.validate.outputs.repository }}
      validation_output: ${{ steps.validate.outputs.validation_output }}
      result: ${{ steps.validate.outputs.result }}
    steps:
      - name: Parse issue body
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.1

      - name: Find plugin repository
        id: set-output
        env:
          JSON_DATA: ${{ steps.parse.outputs.data }}
        run: |
          repository=$(echo $JSON_DATA | jq -r '.["alice-bot-plugin-repository-name"].text' )
          echo "repository=$repository" >> $GITHUB_OUTPUT

      - name: Ensure repository is filled
        if: steps.set-output.outputs.repository == 'null'
        env:
          PARSED_DATA: ${{ steps.parse.outputs.data }}
        run: |
          # Check if $GITHUB_STEP_SUMMARY exist to avoid the following lines to error when running with act
          if [[ -w "$GITHUB_STEP_SUMMARY" ]]; then
            echo "No repository found in the body of the issue ${{ inputs.issue_number }}" >> $GITHUB_STEP_SUMMARY
            echo "Is the \"alice-bot-plugin-repository-name\" field present?" >> $GITHUB_STEP_SUMMARY
            echo $PARSED_DATA >> $GITHUB_STEP_SUMMARY
          fi
          exit 1

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate repository
        id: validate
        env:
          REPOSITORY: ${{ steps.set-output.outputs.repository }}
        run: node .github/actions-scripts/validate.js

  create-pr:
    runs-on: ubuntu-latest
    needs: parse-issue
    if: needs.parse-issue.outputs.result == 'success'
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUM: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      CONTENT: ${{needs.parse-issue.outputs.validation_output}}
    outputs:
      result: ${{ steps.copy-commands.outputs.result }}
      file_json: ${{ steps.read-json.outputs.file_json }}
    steps:
      - name: Get open linked PR
        id: get_open_linked_pr
        run: |
          open_linked_pr_length=$(\
            gh pr list \
              --repo $REPO \
              --state open \
              --search "close #$ISSUE_NUM in:body" \
              --json number | jq '. | length'\
          )
          echo "::set-output name=open_linked_pr_length::$open_linked_pr_length"

      - name: Check open linked pr length
        if: steps.get_open_linked_pr.outputs.open_linked_pr_length != 0
        run: |
          echo "Unclosed pull request is existing."
          exit 1

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Get merged linked PR
      #   id: get_merged_linked_pr
      #   run: |
      #     merged_linked_pr_length=$(\
      #       gh pr list \
      #         --repo $REPO \
      #         --state merged \
      #         --search "close #$ISSUE_NUM in:body" \
      #         --json  number | jq '. | length'\
      #     )
      #     echo "::set-output name=merged_linked_pr_length::$merged_linked_pr_length"
      - name: update JSON file
        id: validate
        env:
          VALUES: ${{needs.parse-issue.outputs.validation_output}}
          FILE: "plugins.json"
        run: node .github/actions-scripts/file.js

      # - name: Create files
      #   # if: steps.get_merged_linked_pr.outputs.merged_linked_pr_length == 0
      #   run: |
      #     echo -e "${CONTENT}" \
      #       >> config.json

      - name: Reopen issue
        if: ${{ github.event.issue.state }} == "closed"
        run: gh issue reopen $ISSUE_NUM

      - name: Define new branch name
        id: define_new_branch_name
        run: |
          new_branch_name=$(echo "${ISSUE_NUM}-$(TZ=UTC-9 date '+%Y%m%d')")
          echo "::set-output name=new_branch_name::$new_branch_name"

      - name: Create branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ steps.define_new_branch_name.outputs.new_branch_name }}

      - name: Create PR
        run: |
          gh pr create \
            --head $NEW_BRANCH_NAME \
            --base $BASE_BRANCH_NAME \
            --title "$ISSUE_TITLE" \
            --body "close #${ISSUE_NUM}"
        env:
          NEW_BRANCH_NAME: ${{ steps.define_new_branch_name.outputs.new_branch_name }}
          BASE_BRANCH_NAME: ${{ github.event.repository.default_branch }}

      - name: Copy Commands
        id: copy-commands
        run: |
          echo "git fetch origin ${NEW_BRANCH}"
          echo "git checkout ${NEW_BRANCH}"
          echo "code --reuse-window plugins.json"
          result="success"
          echo "result=$result" >> $GITHUB_OUTPUT
        env:
          NEW_BRANCH: ${{ steps.define_new_branch_name.outputs.new_branch_name }}

  validation-succeeded:
    runs-on: ubuntu-latest
    needs: create-pr
    if: needs.create-pr.outputs.result == 'success'
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Render template
        id: render
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/workflows/templates/validation-succeeded.md
          vars: |
            extension: ${{ needs.parse-issue.outputs.validation_output }}
            content: ${{ needs.parse-issue.outputs.repository }}

      - name: Add Comment
        if: env.ACT == false
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.render.outputs.result }}

      - name: Remove label validation/failed
        if: env.ACT == false && contains(github.event.issue.labels.*.name, 'validation/failed')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["validation/failed"]
            })

      - name: Add label validation/succeeded
        if: env.ACT == false && !contains(github.event.issue.labels.*.name, 'validation/succeeded')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["validation/succeeded"]
            })

  validation-failed:
    runs-on: ubuntu-latest
    needs: parse-issue
    if: needs.parse-issue.outputs.result == 'failure'
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Render template
        id: render
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/workflows/templates/validation-failed.md
          vars: |
            extension: ${{ needs.parse-issue.outputs.repository }}
            validation_output: ${{ toJSON(format('{0}{1}', needs.parse-issue.outputs.validation_output,needs.parse-issue.outputs.validation_output)) }}

      - name: Add comment
        if: env.ACT == false
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.render.outputs.result }}

      - name: Remove label validation/succeeded
        if: env.ACT == false && contains(github.event.issue.labels.*.name, 'validation/succeeded')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["validation/succeeded"]
            })

      - name: Add label validation/failed
        if: env.ACT == false && !contains(github.event.issue.labels.*.name, 'validation/failed')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["validation/failed"]
            })

      - name: Mark job as failed
        run: exit 1
